[package]
name = "rixel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy-inspector-egui = "0.14.0"
bevy_ecs_tilemap = "0.9.0"
itertools = "0.10.5"
rand = "0.8.5"
wgpu = "0.14.2"
